default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: <%= ENV.fetch('DATABASE_HOSTNAME', 'db') %>
  port: 3306
  timeout: 5000
  charset: utf8
  collation: utf8_unicode_ci

development:
  <<: *default
  database: teamlab_selection_task_development

test:
  <<: *default
  database: teamlab_selection_task_test

production:
  <<: *default
  host: <%= Rails.application.credentials.rds[:host] %>
  database: <%= Rails.application.credentials.rds[:database] %>
  username: <%= Rails.application.credentials.rds[:username] %>
  password: <%= Rails.application.credentials.rds[:password] %>
